{{- if and .Values.tls.enabled .Values.tls.certs.certManager.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '0'
  # This is referenced from the upstream default values, plz no change me
  # https://github.com/cockroachdb/helm-charts/blob/c57245c47289153dd7c2f86bdc83ce7b1b6cab59/cockroachdb/values.yaml#L485
  name: {{ .Values.tls.certs.certManagerIssuer.name }}
spec:
  ca:
    secretName: {{ .Values.tls.certs.certManager.existingSercet.name }}
{{- end -}}